version: 'v0.0.1'

services:
  frontend:
    restart: always
    image: hitsql/frontend:latest
    hostname: frontend
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    restart: always
    image: hitsql/backend:latest
    hostname: backend
    container_name: backend
    build: ./backend
    # ports:
    #   - '8000:8000'