# Generated by Django 5.0.2 on 2024-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranspiledSQL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("input_sql", models.TextField(default="")),
                ("output_sql", models.TextField(default="")),
                (
                    "input_dialect",
                    models.CharField(
                        choices=[
                            ("bigquery", "bigquery"),
                            ("clickhouse", "clickhouse"),
                            ("databricks", "databricks"),
                            ("doris", "doris"),
                            ("drill", "drill"),
                            ("duckdb", "duckdb"),
                            ("hive", "hive"),
                            ("mysql", "mysql"),
                            ("oracle", "oracle"),
                            ("postgres", "postgres"),
                            ("presto", "presto"),
                            ("redshift", "redshift"),
                            ("snowflake", "snowflake"),
                            ("spark", "spark"),
                            ("spark2", "spark2"),
                            ("sqlite", "sqlite"),
                            ("starrocks", "starrocks"),
                            ("tableau", "tableau"),
                            ("teradata", "teradata"),
                            ("trino", "trino"),
                            ("tsql", "tsql"),
                        ],
                        default="mysql",
                        max_length=10,
                    ),
                ),
                (
                    "output_dialect",
                    models.CharField(
                        choices=[
                            ("bigquery", "bigquery"),
                            ("clickhouse", "clickhouse"),
                            ("databricks", "databricks"),
                            ("doris", "doris"),
                            ("drill", "drill"),
                            ("duckdb", "duckdb"),
                            ("hive", "hive"),
                            ("mysql", "mysql"),
                            ("oracle", "oracle"),
                            ("postgres", "postgres"),
                            ("presto", "presto"),
                            ("redshift", "redshift"),
                            ("snowflake", "snowflake"),
                            ("spark", "spark"),
                            ("spark2", "spark2"),
                            ("sqlite", "sqlite"),
                            ("starrocks", "starrocks"),
                            ("tableau", "tableau"),
                            ("teradata", "teradata"),
                            ("trino", "trino"),
                            ("tsql", "tsql"),
                        ],
                        default="hive",
                        max_length=10,
                    ),
                ),
                (
                    "is_transpiled",
                    models.CharField(
                        choices=[("0", "0"), ("1", "1")], default="0", max_length=1
                    ),
                ),
                ("errs_msg", models.TextField(default="")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
